ENH: Allow failing the action with fail-on-differences boolean flag

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -16,6 +16,11 @@ inputs:
     description: >
       Compare the recorded submodule reference with SUB-BRANCH in each submodule (default: master).
     required: false
+  fail-on-differences:
+    description: >
+      Boolean flag whether to fail the action if there are any differences between the superproject and submodule references.
+    required: false
+    default: false
 outputs:
   differences-found:
     description: >
@@ -38,16 +43,26 @@ runs:
         MESSAGE: ${{ inputs.message }}
         SUPER_BASE: ${{ inputs.super-base }}
         SUBMODULE_BASE: ${{ inputs.submodule-base }}
+        FAIL_ON_DIFFERENCES: ${{ inputs.fail-on-differences }}
       run: |
         git config --global --add include.path "${GITHUB_WORKSPACE}/git-extensions/gitconfig"
         PATH="${GITHUB_WORKSPACE}/git-extensions/bin:${PATH}"
 
         typeset -ar statusToBoolean=(true false)
-        typeset -ar statusToAnnotation=(warning notice error)
+        case "$FAIL_ON_DIFFERENCES" in
+          true)   typeset -ar statusToAnnotation=(error notice error)
+                  typeset -ar statusToFinalStatus=(1 0)
+                  ;;
+          false)  typeset -ar statusToAnnotation=(warning notice error)
+                  typeset -ar statusToFinalStatus=(0 0)
+                  ;;
+          *)      printf >&2 'ERROR: Invalid fail-on-differences: %s\n' "$FAIL_ON_DIFFERENCES"; exit 2;;
+        esac
         typeset -ar statusToMessage=('Differences found between superproject and submodule(s)' 'No differences found between superproject and submodule(s)' 'An unexpected error occurred')
 
         status=0; logs="$(git-supersubinout ${MESSAGE:+--message "$MESSAGE"} ${SUPER_BASE:+--super-base "$SUPER_BASE"} ${SUBMODULE_BASE:+--submodule-base "$SUBMODULE_BASE"})" || status=$?
 
         printf 'differences-found=%s\nlogs<<EOF\n%s\nEOF\n' "${statusToBoolean[$status]:-false}" "$logs" >> "$GITHUB_OUTPUT"
         printf '::%s::%s\n' "${statusToAnnotation[$status]:-error}" "${statusToMessage[$status]:-${statusToMessage[2]}}"
+        exit "${statusToFinalStatus[$status]:$status}"
       shell: bash
